workspace:
  base: /go
  path: src/github.com/umputun/remark

pipeline:
  
  build:
    image: golang:1.9-alpine
    commands:
      - cd app
      - go build -v ./...

  docker:
    image: plugins/docker
    repo: umputun/remark
    secrets: [ docker_username, docker_password ]
    tags: ${DRONE_REPO_BRANCH}

  deploy:
    image: appleboy/drone-ssh
    host: remark42.com
    username: umputun
    port: 22
    secrets: [ ssh_key ]
    script:
      - cd /srv/remark
      - docker-compose pull
      - docker-compose up -d
    when:
      branch: master

  notify:
    image: drillster/drone-email
    host: homei.umputun.com
    port: 25
    skip_verify: true
    from: drone@umputun.com
    recipients: [ umputun@gmail.com ]
    when:
      status: [ changed, failure ]
