version: '2'

services:

    remark:
        build: .
        image: umputun/remark:develop
        container_name: "remark"
        hostname: "remark"
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        environment:
            - MHOST=${MHOST}

        ports:
            - "8080:8080"

        environment:
            - BOLTDB_FILE=/srv/var/remark.db
            - SESSION_STORE=/srv/var
            - DEV=true
            - DEBUG=true

        volumes:
            - ./var:/srv/var

