name: Github Actions CI

on:
  push:
    branches:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker version
      run: docker version
    - name: Debug if needed
      run: |
        [[ "$DEBUG" ]] && env
      env:
        DEBUG: ${{secrets.DEBUG}}
    - name: Build image
      run: |
        export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"

        docker build \
        --build-arg CI="$GITHUB_WORKFLOW" \
        --build-arg GIT_BRANCH=$GIT_BRANCH \
        --build-arg COVERALLS_TOKEN=$COVERALLS_TOKEN \
        .
      env:
        COVERALLS_TOKEN: ${{secrets.COVERALLS_TOKEN}}